# DOCKER-VERSION  1.8.3

FROM brianshumate/hubot
MAINTAINER Brian Shumate, brian@couchbase.com

ENV FILE_BRAIN_PATH=""
ENV HUBOT_ANNOUNCE_ROOMS=""
ENV HUBOT_HIPCHAT_TOKEN=""
ENV HUBOT_HIPCHAT_AUTH_TOKEN=""
ENV HUBOT_HIPCHAT_JID=""
ENV HUBOT_HIPCHAT_NAME=""
ENV HUBOT_HIPCHAT_PASSWORD=""
ENV HUBOT_HIPCHAT_ROOMS=""
ENV HUBOT_HIPCHAT_JOIN_ROOMS_ON_INVITE=""
ENV HUBOT_JIRA_URL=""
ENV HUBOT_JIRA_USER=""
ENV HUBOT_JIRA_PASSWORD=""
ENV HUBOT_ZENDESK_USER=""
ENV HUBOT_ZENDESK_PASSWORD=""
ENV HUBOT_ZENDESK_SUBDOMAIN=""
ENV WORDNIK_API_KEY=""
ENV HUBOT_WUNDERGROUND_API_KEY=""
ENV HUBOT_PORT 8073
ENV NODE_MODULES=""
EXPOSE ${HUBOT_PORT}

WORKDIR /opt/hubot

RUN npm install ${NODE_MODULES}

RUN npm install

CMD bin/hubot

