---
# File: tasks/main.yml - Ansible Hubot main tasks

# CentOS/RHEL tasks
- include: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Debian/Ubuntu tasks
- include: Debian.yml
  when: ansible_os_family  == "Debian"
