---
# File: tasks/main.yml - Ansible Hubot main tasks

- name: Use OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# CentOS/RHEL tasks
- include: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Debian/Ubuntu tasks
- include: Debian.yml
  when: ansible_os_family  == "Debian"
